### ISSUE TITLE
Insufficient Permissions

### ISSUE THREAD

**Issue by andre-meneses-fivestars** [P403n1x87/austin#138]
### Description

When I try to run austin to attach to a process I get Insufficient permissions even if I run with sudo or with root user, or with root user using sudo.
If I try to go the way of `sudo setcap cap_sys_ptrace+ep 'which austin'`, after running this command, when I try to launch austin I get `Operation not permitted`

### Steps to Reproduce

1. Clone and build austin with gcc
2. Try to run with sudo using -p either using sudo or setting setcap cap_sys_ptrace+ep

**Expected behavior:** [What you expect to happen]
austin should start normally

**Actual behavior:** [What actually happens]
I either get "Insufficient permissions" from austin or `Operation not permitted` from the OS

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time

### Versions

You can get this information from copy and pasting the output of `austin
--version` from the command line. Also, please include the OS and what version
of the OS you're running.
austin 3.3.0
Debian GNU/Linux 11 (bullseye)

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by P403n1x87** [comment]
@andre-meneses-fivestars thanks for reporting this. Can I check a couple of things with you, please? Firstly, please note that the `setcap` command requires _backticks_ for the `which austin` part. Since you are compiling from sources, the binary will probably be in the `src` folder, so you should run
~~~ console
sudo setcap cap_sys_ptrace+ep src/austin
~~~
from the project's folder.

Secondly, would you be able to share some details about the kind of application that you're trying to attach to? Is it a pure Python application? An application that embeds Python? What's the full command that you are using to attach? Does

~~~ console
src/austin python3 -c "import time; time.sleep(3)"
~~~
work?

Thanks.

**Comment by andre-meneses-fivestars** [comment]
Hi @P403n1x87, and thank you for your quick reply.

I know `which austin` requires backticks. I was getting a hard time getting those to work here with Markdown and just replaced with the other, but ran it correctly on the machine.

Also, I could confirm that ```src/austin python3 -c "import time; time.sleep(3)"``` works.

I am trying to profile an Python api, that is running behind uwsgi, and I was trying to attach to the uwsgi process. Is there any way I can make austin work that way?

**Comment by P403n1x87** [comment]
> I am trying to profile an Python api, that is running behind uwsgi, and I was trying to attach to the uwsgi process. Is there any way I can make austin work that way?

@andre-meneses-fivestars thanks for the feedback. Have you tried with the `-C/--children` option? The parent uwsgi process is likely not a Python process, so you would have to instruct Austin to look for its children. Alternatively, you could try to locate the child processes manually, which are likely to be Python processes and attach to one of them.

**Comment by andre-meneses-fivestars** [comment]
@P403n1x87 just want to leave you with the current status.
The only processes are uwsgi ones. There is one parent and several children/workers.
If I use the `-p, --pid=PID` parameter, I always get the "insufficient permissions" message. If I use the `-C, --children` (on either the parent or children uwsgi processes) I get `👽 Not a Python process.`and later in the message `😣 No samples collected.`

The python process seems to be embedded somehow in uwsgi. I don't really understand how it works, but it seems I would have to run it any other way to get some results :/

**Comment by P403n1x87** [comment]
@andre-meneses-fivestars thanks for the updates. How is uwsgi installed? What version are you running? If the embedded Python (normally a shared library) hasn't been stripped of symbols, then Austin should work. I'll see if I can reproduce the issue once I know which version of uwsgi (and from which source) to target.

**Comment by andre-meneses-fivestars** [comment]
@P403n1x87 uwsgi is installed through Poetry/Pip. The version we're using is 2.0.18.
Thank you for all your assistance.

**Comment by P403n1x87** [comment]
@andre-meneses-fivestars 3.4.1 is out now, if you can give it a try. I will do some testing on my part in the coming days.

**Comment by P403n1x87** [comment]
@andre-meneses-fivestars I have just tested uwsgi==2.0.18 from pip on Ubuntu 22.04 and Python 3.9. I'm using this sample app:
~~~ python
from time import sleep


def application(env, start_response):
    sleep(3)

    start_response('200 OK', [('Content-Type','text/html')])

    return [b"Hello World"]
~~~
I've run it with 
~~~ console
uwsgi --http :9090 --wsgi-file foobar.py --master --processes 2 --threads 2
~~~
and got the following processes
~~~ console
...
spawned uWSGI master process (pid: 29667)
spawned uWSGI worker 1 (pid: 29668, cores: 2)
spawned uWSGI worker 2 (pid: 29669, cores: 2)
spawned uWSGI http 1 (pid: 29670)
...
~~~
Attaching to 29668 with `austin -i 1s -p 29668` and sending a request to `http://localhost:9090` produces (I'm using Austin 3.4.1)
~~~
...
P29668;T29668 1000120
P29668;T29671 1000123
P29668;T29668;foobar.py:application:5 1000123
P29668;T29671 1000118
P29668;T29668;foobar.py:application:5 1000118
P29668;T29671 1000168
P29668;T29668;foobar.py:application:5 1000168
P29668;T29671 1000084
P29668;T29668 1000084
...
~~~
Are you perhaps using some other options with uwsgi that I have not used here? In my case, `ldd` shows that I'm using the shared Python library from the system
~~~
ldd `which uwsgi`
	linux-vdso.so.1 (0x00007ffe7e983000)
	libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007fcd2bbf4000)
	libz.so.1 => /usr/lib/x86_64-linux-gnu/libz.so.1 (0x00007fcd2bbd8000)
	libpcre.so.3 => /usr/lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fcd2bb62000)
	libuuid.so.1 => /usr/lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fcd2bb59000)
	libssl.so.3 => /usr/lib/x86_64-linux-gnu/libssl.so.3 (0x00007fcd2bab5000)
	libcrypto.so.3 => /usr/lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007fcd2b671000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fcd2b48f000)
	libcrypt.so.1 => /usr/lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fcd2b455000)
	libpython3.9.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.9.so.1.0 (0x00007fcd2aebc000)
	libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007fcd2ac94000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcd2be27000)
	libicuuc.so.70 => /lib/x86_64-linux-gnu/libicuuc.so.70 (0x00007fcd2aa7d000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fcd2aa50000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fcd2aa1f000)
	libicudata.so.70 => /lib/x86_64-linux-gnu/libicudata.so.70 (0x00007fcd28e01000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fcd28bd7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fcd28bb7000)
~~~
