### ISSUE TITLE
austinp only builds on systems with a patched libbfd

### ISSUE THREAD

**Issue by delroth** [P403n1x87/austin#152]
### Description

libbfd is weird. The upstream version of bfd.h contains the following:

```
/* PR 14072: Ensure that config.h is included first.  */
#if !defined PACKAGE && !defined PACKAGE_VERSION
#error config.h must be included before this header
#endif
```

This has been reported at least twice ([1](https://sourceware.org/bugzilla/show_bug.cgi?id=14243) [2](https://sourceware.org/bugzilla/show_bug.cgi?id=15920)) to upstream binutils, and closed as WONTFIX because binutils maintainers think it should be every downstream user's problem to comply with that weird PACKAGE/PACKAGE_VERSION define requirement.

It happens that several Linux distros carry downstream patches to remove this part of the bfd.h header, which allows austinp to build on those systems. That includes [Debian (and derivatives)](https://salsa.debian.org/toolchain-team/binutils/-/blob/master/debian/rules#L1120-1123) as well as [Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=845084) (who also qualified the behavior as "clearly wrong"...). Unfortunately, this is not universally carried by distros: Arch and NixOS don't carry this patch (though I'm looking at adding it to NixOS now).

To allow austinp to build on more Linux distributions, it would be good to have a workaround for this. It could be as easy as what `perf` is currently doing: https://elixir.bootlin.com/linux/latest/source/tools/perf/util/srcline.c#L132

If you're fine with that I'm happy to send a PR to add that "#define PACKAGE" before bfd.h includes, but I suspect it will be faster for you to just make the commit :) just let me know.

### Steps to Reproduce

1. Build austinp on a Linux distro that does not carry the aforementioned bfd.h patch. Arch or NixOS are widely used distros that fit this criteria.

**Expected behavior:** austinp is able to use the system's unpatched bfd.h

**Actual behavior:** compilation error:

```
#error config.h must be included before this header
```

**Reproduces how often:** 100%

### Versions

3.4.1

### Additional Information

n/a

**Comment by P403n1x87** [comment]
@delroth thanks for reporting this! I was not aware of this issue with `libbfd`. So the fix is to just define `PACKAGE` somewhere? I believe this wouldn't be a problem. I'll try to give it a test and fix this for future releases. Hopefully, the pre-built binaries in the releases here on GitHub should obviate this issue for anybody wanting to use `austinp` where it currently doesn't build.
