### ISSUE TITLE
Tracing a program running inside docker container may fail

### ISSUE THREAD

**Issue by alexbozhenko** [P403n1x87/austin#159]
### Description

Hi, Gabriele.
Below is my understanding of the problem, please tell me where I am wrong.
Austin is trying to get python interpreter path by reading [proc/maps](https://github.com/P403n1x87/austin/blob/413948144ca09bcddd976eb7fd001fc24973f7d4/src/linux/py_proc.h#L358).
When running inside a docker container, that file will contain paths that are relative to the container, and those paths make sense only inside the container.

Austin will then try to check that file using the path on the host system here:
[on the host system](https://github.com/P403n1x87/austin/blob/413948144ca09bcddd976eb7fd001fc24973f7d4/src/linux/py_proc.h#L330)

### Steps to Reproduce
Run any python program inside the docker container, and trace it with Austin. I will provide exact steps if needed, but I wanted to hear your thoughts first.

**Expected behavior:** Not sure... Allow Austin to specify the path to the interpreter, somehow expose the interpreter from the container to the host, and then manually let austin know which interpreter to use?
My use case is actually even more trickier: I wanted to run Austin from a container(with host PID namespace and admin privileges), to trace a program in another container...
Somehow it works with https://github.com/benfred/py-spy, but I haven't dug into how it works...

**Actual behavior:** 

- If python interpreters on the host and in the container are the same, it will work(I guess)
- If the container's python version does not exist on the host, Austin will fail with the "not a python process" message
- If the python path exists both on the host and in the container(e.g. `/usr/bin/python3.7`), but their versions are different, Austin will produce an empty output. 

### Versions
Latest Austin version from github. Ubuntu 18 for the host system, Ubuntu 18 inside the container.

**Comment by P403n1x87** [comment]
@alexbozhenko your analysis is correct. Austin was not designed to handle processes running inside a container from the host system. As you described, there is still a chance that Austin might accidentally work, and that's when both the container and the host have the same interpreter version at the same path.

One way to fix this is perhaps reading the ELF data from the memory maps instead of going to the backing file on disk.

**Comment by alexbozhenko** [comment]
Thanks for looking into this!

I think that would be a nice feature.
It looks like py_spy does something along those lines in
https://github.com/benfred/py-spy/blob/c325f41b6c9a2ba984acc131b7d764c424ad44e8/src/python_process_info.rs#L286

**Comment by P403n1x87** [comment]
@alexbozhenko it should now be possible to profile processes running in Docker from the host environment. The change has been merged into the `devel` branch. Would you be able to give that try by any chance? 🙏

**Comment by alexbozhenko** [comment]
Hi, @P403n1x87. Thanks again for looking into it!

I still see empty output file, and these lines in the logs when I run it against a program running inside a container:
```
...
Jan 04 20:27:11 austin[446809]: Cannot open binary file /usr/bin/python3.7
Jan 04 20:27:11 austin[446809]: Cannot open binary file /usr/bin/python3.7
Jan 04 20:27:11 austin[446809]: No remote symbol references have been set.
Jan 04 20:27:11 austin[446809]: Cannot read remote memory
```

**Comment by P403n1x87** [comment]
Ah crikey. I've added a test case that simulates the scenario where the binaries are not available, like in the case of containers and it seems to work. I'll try to have another look at it. Thanks for giving this a spin!

**Comment by P403n1x87** [comment]
@alexbozhenko I've done some more testing and pushed a minor fix. I've got Austin to work with systemd containers. I'd appreciate it if you could give it another try at your best convenience. Cheers!

**Comment by alexbozhenko** [comment]
thanks @P403n1x87 it does work with the latest change!

```
./austin -C       -p 1311834 --output austin.out
              _   _
 __ _ _  _ __| |_(_)_ _
/ _` | || (_-<  _| | ' \
\__,_|\_,_/__/\__|_|_||_| 3.5.0 [GCC 9.4.0]

Parent process

🐍 Python version: 3.7.0

Child processes

🐍 Python version: 3.7.0
...
```

**Comment by P403n1x87** [comment]
🎉  Thanks for testing and confirming this, @alexbozhenko 🙌
