### ISSUE TITLE
both austin-web and austin-tui don't accept -m flag

### ISSUE THREAD

**Issue by nbecker** [P403n1x87/austin#32]
### Description
austin-web -p 17118 -m
usage: austin-web [-h] [-a] [-e] [-i INTERVAL] [-p PID] [-s] [-t TIMEOUT]
                  [command] [args [args ...]]
austin-web: error: unrecognized arguments: -m

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
I expected -m would be passed to austin to give memeory profile

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `austin
--version` from the command line. Also, please include the OS and what version
of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by P403n1x87** [comment]
Hi and many thanks for your interest in the TUI and Web tools. As stated in the README, these are just sample applications to show how one can use Austin to make more complex applications. As such, they do not get the same development focus as Austin and therefore tend to lag behind with the support of the latest features. However, given that you have expressed interest in using these tools I will try to add support for the -m flags and other new features as soon as I will find the time.

**Comment by P403n1x87** [comment]
@nbecker  I have opened #34 as a candidate for closing #32. Would you be able to give it a go and see if it is enough for your needs/report any bugs?

`pip3 install git+https://github.com/P403n1x87/austin.git@feature/memory_tui_web`

Thanks,
G
