### ISSUE TITLE
How dose it work with gunicorn?

### ISSUE THREAD

**Issue by koolay** [P403n1x87/austin#40]
I want to profiling my web app running on gunicorn server.

**Comment by P403n1x87** [comment]
@koolay once you have started the gunicorn server, get hold of the root process ID and attach Austin to it with the `-C` flag. For example, on Linux, assuming that `pgrep gunicorn | head -n 1` returns the root process ID of the gunicorn server,

~~~ bash
sudo austin -Cp `pgrep gunicorn | head -n 1`
~~~

This will start profiling all the processes spawned by gunicorn. If you want to profile just one process, get hold of its PID and attach to that instead, e.g.

~~~ bash
sudo austin -p `pgrep gunicorn | tail -n 1`
~~~
