### ISSUE TITLE
py3.8: AttributeError: 'NoneType' object has no attribute 'memory'

### ISSUE THREAD

**Issue by nbecker** [P403n1x87/austin#42]
### Description
 austin-web -p 5301
_____      ___       __    ______       _______              __________             _____  
____/|_    __ |     / /_______  /_      ___    |___  __________  /___(_)______      ____/|_
_|    /    __ | /| / /_  _ \_  __ \     __  /| |  / / /_  ___/  __/_  /__  __ \     _|    /
/_ __|     __ |/ |/ / /  __/  /_/ /     _  ___ / /_/ /_(__  )/ /_ _  / _  / / /     /_ __| 
 |/        ____/|__/  \___//_.___/      /_/  |_\__,_/ /____/ \__/ /_/  /_/ /_/       |/    
                                                                                           

* Sampling process with PID 5301 (/usr/bin/python3 ./test1c.py --mod=qpsk,8+8apsk --rate=1/4,26/45 --esno=6.8 --bicm --real --demod-iter=10 --clip=100)
* Web Austin is running on http://localhost:59115. Press Ctrl+C to stop.
Error handling request
Traceback (most recent call last):
  File "/home/nbecker/.local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/nbecker/.local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/nbecker/.local/lib/python3.8/site-packages/austin/web.py", line 170, in handle_websocket
    "metric": "m" if self.args.memory else "t",
AttributeError: 'NoneType' object has no attribute 'memory'
[Description of the issue]

### Steps to Reproduce

1. [First Step]
Start code to be profiled
2. [Second Step]
Start austin-web -p pid
3. [and so on...]
When web page is opened, above error results

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
python3.8, fedora 32 linux

You can get this information from copy and pasting the output of `austin
--version` from the command line. Also, please include the OS and what version
of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by P403n1x87** [comment]
Hi there. Thanks for reporting this issue. I just wanted to give a bit of an update. I am in the process of factoring out the Python code out of this repository and create dedicated repositories for each of the tools. Hence, this issue will be addressed during the refactoring, which hopefully won't take too long!

**Comment by P403n1x87** [comment]
This has been fixed here https://github.com/jurgisp/austin/commit/476b237be03296a6715eadaf440e4f141e4237f5

**Comment by P403n1x87** [comment]
Fixed by [austin-web@v0.1.0](https://github.com/p403n1x87/austin-web).
