### ISSUE TITLE
Did not get desired results | `🐢 Long sampling rate : 80722/83336 (96.86 %) samples took longer than the sampling interval`

### ISSUE THREAD

**Issue by pra-dan** [P403n1x87/austin#47]
### Description
I try to profile my Python script using Austin but fail. I 

### Steps to Reproduce

1. Create python script:
```
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
import numpy as np

from memory_profiler import profile
#fp=open('memory_profile.log','w+')
@profile()
def import_data():
    data=pd.read_csv("kc_house_data.csv")
    data=data.drop(["id","date"],axis=1)
    data["sqft_above"].fillna(1788.39,inplace=True)
    return data
    #data.describe()

@profile()
def parse_data(data):
    Y=data["price"].va[What actually happens]lues
    Y=np.log(Y)
    features=data.columns
    X1=list(set(features)-set(["price"]))
    X=data[X1].values
    ss=StandardScaler()
    X=ss.fit_transform(X)
    return X,Y

@profile()
def linearRegressionfit(Xt,Yt,Xts,Yts):
    lr=LinearRegression()
    model=lr.fit(Xt,Yt)
    predict=lr.predict(Xts)

    print("train Accuracy",lr.score(Xt,Yt))
    print("test Accuracy",lr.score(Xts,Yts))

@profile()
def randForestRegressorfit(Xt,Yt,Xts,Yts):
    regr = RandomForestRegressor(n_estimators=100,max_features='auto',max_depth=80 ,min_samples_leaf=1
                                 ,min_samples_split=2,random_state=0)
    model=regr.fit(Xt,Yt)
    predict=regr.predict(Xts)
    print("train Accuracy : ",regr.score(Xt,Yt))
    print("test Accuracy : ",regr.score(Xts,Yts))


if __name__ == '__main__':
    data = import_data()
    X, Y = parse_data(data)
    Xt,Xts,Yt,Yts=train_test_split(X,Y,test_size=0.4,random_state=0)
    linearRegressionfit(Xt,Yt,Xts,Yts)

    randForestRegressorfit(Xt,Yt,Xts,Yts)
    linearRegressionfit(Xt,Yt,Xts,Yts)
```
2. Get the dataset from [kc_house_data.zip](https://github.com/P403n1x87/austin/files/4673076/kc_house_data.zip)

3. Run the code: `$ austin -i 50 python main.py | FlameGraph/flamegraph.pl > my_script_profile.svg
`

**Expected behavior:** CPU usage and other profiliing stats are saved/plotted on a flamegraph

**Actual behavior:** Got an error: 
```
🕑 Sampling time (min/avg/max) : 1/257/8625 us
🐢 Long sampling rate : 80722/83336 (96.86 %) samples took longer than the sampling interval
💀 Error rate : 0/83336 (0.00 %) invalid samples
```

**Reproduces how often:** 100%

### Versions

Austin: 1.0.1
OS: Ubuntu 18.04.4 LTS

**Comment by P403n1x87** [comment]
Hi there. Thanks for reporting this. The stars that are printed at the end so not indicate an error. You have asked for a sampling interval of 50 microseconds but Austin was able to sample at 257 on average. Hence almost 97% of the samples took longer than 50 microseconds. Add for the samples themselves, it looks as if Austin collected 83336 of them so good should definitely have something in the SVG file. If not, could you try to output samples to a file with e.g.

**Comment by pra-dan** [comment]
Hey @P403n1x87 

Firstly, KUDOS to this work. :thumbs-up:


Yeah you are right about the _having something_. I do have the following svg stored: 
![Screenshot from 2020-05-24 15-26-38](https://user-images.githubusercontent.com/46529961/82751161-0a9dde80-9dd3-11ea-893b-db087a4be0dc.png)
But I think it fails the purpose as I can hardly interpret anything from it. Please suggest how I could profile the CPU-usage and function branching using Austin.

**Comment by P403n1x87** [comment]
@pra-dan thanks for confirming that Austin produced the samples correctly :). As for the interpretation of the result, Austin is a sampling profiler that just returns snapshots of the internal state of the interpreter at regular intervals. The function branching in flamegraph is represented by stacks. You are probably not interested in the tall stacks because they normally represent initialisation work done by CPython at startup.

You can then either click on the base of the middle part to zoom in the part of interest, or use the search feature of the flamegraph. See https://github.com/brendangregg/FlameGraph for more details on how to use the flamegraph. Alternatively, you could use the austin2speedscope script to convert the output from Austin into the Speedscope format. See the README for the steps required.
