### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by exhuma** [P403n1x87/austin#48]
### Description

Unable to compile

### Steps to Reproduce

1. Clone the repo at revision `679a896`
2. run `gcc -O3 -Wall -pthread src/*.c -o src/austin`

**Expected behavior:**

Compilation should run

**Actual behavior:**

The following error shows up:

```
› gcc -O3 -Wall -DDEBUG -pthread src/*.c -o src/austin
src/py_proc.c: In function ‘py_proc__sample’:
src/py_proc.c:918:44: warning: ‘current_thread’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if (self->py_runtime_raddr != NULL && current_thread == (void *) -1) {
                                            ^
```

**Reproduces how often:** 100%

**Comment by P403n1x87** [comment]
Hi @exhuma. This is just a warning and can be ignored. The binary `src/austin` should work as expected.
