### ISSUE TITLE
Running austin fails with "no such process"

### ISSUE THREAD

**Issue by jorgsk** [P403n1x87/austin#50]
### Description

Running austin on any file fails with the output "no such process".

### Steps to Reproduce

1. Installed Austin first with autotools then with snap on xubuntu 18.04
2. ran Austin on test script as described in readme file: "austin -i 50 ./test.py"

**Expected behavior:** [What you expect to happen]
Program ran

**Actual behavior:** [What actually happens]
"no such process" given as output

**Reproduces how often:** [What percentage of the time does it reproduce?]
100 %

### Versions

1.0.1

### Additional Information

I tried to run tests to see if that could help identify the problem, but I didn't figure out how to actually run the tests.

**Comment by P403n1x87** [comment]
Hi. Austin can't parse the command line arguments like a shell does, so you will have to explicitly invoke the interpreter, like so

~~~ bash
$ austin -i 50 python3 ./test.py
~~~

Note that you can also pass the whole shebang (without `#!` of course) to mimick script invocation, e.g.

~~~ bash
$ austin -i 50 /usr/bin/env python3 ./test.py
~~~
