### ISSUE TITLE
Insufficient permissions message on Austin usage command on macOS

### ISSUE THREAD

**Issue by kevchn** [P403n1x87/austin#61]
### Description
I installed austin using brew and am encountering a permissions issue. I saw that there is a ```sudo setcap cap_sys_ptrace+ep `which austin``` step, but I skipped it `setcap` isn't available on macOS and I'm unsure of what to execute instead.

[Description of the issue]

### Steps to Reproduce

1. brew install austin
2. sudo austin

**Expected behavior:** Austin launches

**Actual behavior:**
Error message: 
```Usage: austin [-aCefms?V] [-i n_us] [-o FILE] [-p PID] [-t n_ms] [-x n_sec]
            [--alt-format] [--children] [--exclude-empty] [--full]
            [--interval=n_us] [--memory] [--output=FILE] [--pid=PID]
            [--sleepless] [--timeout=n_ms] [--exposure=n_sec] [--help]
            [--usage] [--version] command [ARG...]

              _   _      
 __ _ _  _ __| |_(_)_ _  
/ _` | || (_-<  _| | ' \ 
\__,_|\_,_/__/\__|_|_||_|
🤓 austin version: 2.0.0

🔒 Insufficient permissions. Austin requires the use of sudo on Mac OS or
that your user is in the procmod group in order to read the memory of even
its child processes. Furthermore, the System Integrity Protection prevents
Austin from working with Python binaries installed in certain areas of the
file system. See

    🌐 https://github.com/P403n1x87/austin#compatibility

for more details.
```

**Reproduces how often:**  100%

**Comment by P403n1x87** [comment]
Hi there. The setcap command is for the Linux platform. On macOS there is the problem of SIP, which is explained in the README (pointed to by the link):

> Due to the System Integrity Protection introduced in MacOS with El Capitan, Austin cannot profile Python processes that use an executable located in the /bin folder, even with sudo. Hence, either run the interpreter from a virtual environment or use a Python interpreter that is installed in, e.g., /Applications or via brew with the default prefix (/usr/local). Even in these cases, though, the use of sudo is required. Alternatively, make sure that the user that is invoking Austin belongs to the procmod group.

**Comment by kevchn** [comment]
Hi, thanks for the reply. I did read the message but unfortunately don't know how to proceed. If I run `sudo alfred` by itself, what does "the interpreter" refer to? I use pyenv to manage my python executables, which aren't in bin/. Thanks in advance.

**Comment by P403n1x87** [comment]
`sudo austin` on its own shows you just the usage. You will have to provide either the command to start a Python application, e.g.

~~~
sudo austin python myapp.py
~~~

or

~~~
sudo austin myapp
~~~

if `myapp` is on the `PATH` variable. If you have a running application that you want to attach to, grab its PID and do

~~~
sudo austin -p <pid>
~~~

**Comment by kevchn** [comment]
Right, I believe there's a bug where running `sudo austin` by itself on macOS, which is supposed to just show usage, shows the `Insufficient Permissions` error - which is supposed to only show up when attaching austin to a Python process without sufficient permissions. 

But this is a minor bug and doesn't impact the utility of austin. Thanks for building this cool tool.

**Comment by kennell** [comment]
I am also getting insufficient permissions on OSX, even when starting austin with a Python script. Austin and Python3 both installed via Homebrew.

```console
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226

$ cat script.py
print("Hello World")

$ which austin
/usr/local/bin/austin

$ which python3
/usr/local/bin/python3

$ sudo austin python3 script.py
              _   _
 __ _ _  _ __| |_(_)_ _
/ _` | || (_-<  _| | ' \
\__,_|\_,_/__/\__|_|_||_|
🤓 austin version: 2.0.0

🔒 Insufficient permissions. Austin requires the use of sudo on Mac OS or
that your user is in the procmod group in order to read the memory of even
its child processes. Furthermore, the System Integrity Protection prevents
Austin from working with Python binaries installed in certain areas of the
file system. See

    🌐 https://github.com/P403n1x87/austin#compatibility

for more details.
```

**Comment by P403n1x87** [comment]
Thanks for your report. CI tests are passing, however, I can reproduce this on Catalina. I suspect this is due to recent updates. As a temporary workaround, disabling SIP *might* allow you to run `austin`. I will have to look for a longer term solution. My feeling is that the `austin` binary now needs the [Debugging Tool Entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_debugger) to work.

**Comment by P403n1x87** [comment]
**Update** The devel version can start/attach to a running REPL.

**Comment by P403n1x87** [comment]
@kennell Your script is too short-lived for Austin to extract any samples. The error message is misleading in this case because the check of whether the process exists is based on the outcome of `task_for_pid`, which could also fail because of permission issues.

**Comment by kennell** [comment]
Thanks, can confirm that with a longer living script austin does indeed work. Maybe adjust the error/warning message accordingly.
