### ISSUE TITLE
Link to MSI from readme

### ISSUE THREAD

**Issue by cool-RR** [P403n1x87/austin#62]
I was looking how to install Austin on Windows. I never used Chocolatey or Scoop before, and I tried to install them but they required PowerShell, and the commands they gave me resulted in errors.

I looked at your Releases page and was happy to see that there's an MSI installer there. That is a much more widely accepted format. I wish the readme stated there's an MSI installer and linked to it. It would have saved me a bunch of time I spent searching, and would likely save others the same.

**Comment by P403n1x87** [comment]
Apologies for the confusion. I will improve the installation instructions with a mention to the MSI in the Releases section
