### ISSUE TITLE
Did the 2.0.0 tarball get created multiple times?

### ISSUE THREAD

**Issue by mitchblank** [P403n1x87/austin#65]
I have been investigating issues with Homebrew formulae that don't build properly from source. One of these is austin. This is because the tarball does not have the expected contents (homebrew is very strict about this for security reasons -- it won't use any external resource if its hash doesn't match what was expected)

Anyway, when I try to install I see:
```
$ brew install -sv austin
==> Downloading https://github.com/P403n1x87/austin/archive/v2.0.0.tar.gz
==> Downloading from https://codeload.github.com/P403n1x87/austin/tar.gz/v2.0.0
##-=#=-#
Error: SHA256 mismatch
Expected: 95d40608bac22b965712dc929143ebc994d44b2eb4782b99ba58a2deb1e38aa1
  Actual: be52b0cb7e0819694929ee525464c903600edd91630ad9c77e486fa38ab934dd
```

The expected SHA comes from when homebrew updated to 2.0.0 on October 8th (cc @chenrui333 )  -- 
 https://github.com/Homebrew/homebrew-core/pull/62498/files

It looks like October 8th was the release date, yet for some reason the archived release tarball seems to have changed.  Did you perhaps rebase your git history or change some other options that might have caused github to recreate the tarball?

**Comment by P403n1x87** [comment]
Thanks for reporting this! I was afraid something like this would happen at some point so I changed the travis job to publish on tag rather than on any push to master. Before I did this though there must have been some new commits on master that retriggered the generation of the release artifacts. This is now unlikely to happen again in the future.

I plan on releasing version 2.1.0 relatively soon, which I presume would "fix" this issue, but perhaps it would be best to have version 2.0.0 in Homebrew working again regardless?

**Comment by mitchblank** [comment]
Thanks for looking into it.  I'll see about getting the homebrew formula building again.

It looks like there are other compile issues for MacOS 11 that need to be sorted out:
```
argparse.c:62:1: error: static declaration of 'strtonum' follows non-static declaration
strtonum(char * str, long * num) {
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:351:2: note: previous declaration is here
        strtonum(const char *__numstr, long long __minval, long long __maxval, const char **__errstrp)
        ^
argparse.c:453:67: error: too few arguments to function call, expected 4, have 2
      strtonum((char *) arg, (long *) &(pargs.t_sampling_interval)) == 1 ||
      ~~~~~~~~                                                    ^
```

**Comment by mitchblank** [comment]
I've started a CI run with the new sha and a hack for the argparse.c issue.  It'll fail initially because homebrew rejects changes where the SHA is updated without the URL changing but the project maintainers can override that: https://github.com/Homebrew/homebrew-core/pull/67648
