### ISSUE TITLE
austin + flamegraph report erroneous code line numers

### ISSUE THREAD

**Issue by AlDanial** [P403n1x87/austin#66]
A recent flamegraph I made with austin showed a large amount of time was being spent on a line number well beyond the end of my source file. I traced the problem to a function whose keyword arguments are split across lines like so:
<pre>
def problem_function(A='qa1',
                     B=None):
</pre>
If the two keyword arguments appear on the same line as with
<pre>
def problem_function(A='qa1', B=None):
</pre>
then the results are correct.

### Steps to Reproduce

The attached programs, derived from https://github.com/danyaal/mandelbrot/blob/master/mandelbrot.py, illustrate the problem.  They differ only in the line split of arguments shown above.  I run the two versions with
<pre>
austin -a -i 50 ./austin_good.py | flamegraph.pl --minwidth 10 --countname=us > flame_good.svg
austin -a -i 50 ./austin_bad.py  | flamegraph.pl --minwidth 10 --countname=us > flame_bad.svg
</pre> 

**Expected behavior:** 
Lines 29 and 27 shown in the flamegraph are correct.
![austin_good](https://user-images.githubusercontent.com/1459933/103182407-e0783780-485f-11eb-9352-08fa4949e2c5.png)

**Actual behavior:**
The bad result suggests a lot of time is spent on line 286--but the file has only 30 lines.
![austin_bad](https://user-images.githubusercontent.com/1459933/103182392-cfc7c180-485f-11eb-9b89-f1d00ea746eb.png)

**Reproduces how often:**  
100%

### Versions
austin 2.0.0
Python 3.8.3 (Anaconda 2020.07)
Ubuntu 20.04

[austin_bad.py.txt](https://github.com/P403n1x87/austin/files/5745492/austin_bad.py.txt)
[austin_good.py.txt](https://github.com/P403n1x87/austin/files/5745493/austin_good.py.txt)

**Comment by P403n1x87** [comment]
Thanks for reporting this issue. A fix is already merged into the `devel` branch (see d0a71f65e7f512f733becd77aeffa24df823a39d) and will be part of the 2.1.0 release.

**Comment by AlDanial** [comment]
d0a71f6 works great, thanks!
