### ISSUE TITLE
Building Austin on Manjaro

### ISSUE THREAD

**Issue by smontanaro** [P403n1x87/austin#69]
### Description

As initially cloned, I was unable to build Austin on my Manjaro system.

### Steps to Reproduce

1. Clone Austin
2. Execute ./configure
3. See errors

**Expected behavior:** Ideally, I would have expected the usual configure system exploration and file generation to occur.

**Actual behavior:** 

```
% ./configure
configure: error: cannot find sources (config.h.in) in . or ..
% autoreconf
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
```
**Solution** On my system, I had an autoconf package installed, but lacked automake. After installing that, I got further:

```
% autoreconf
configure.ac:11: error: required file './compile' not found
configure.ac:11:   'automake --add-missing' can install 'compile'
configure.ac:8: error: required file './install-sh' not found
configure.ac:8:   'automake --add-missing' can install 'install-sh'
configure.ac:8: error: required file './missing' not found
configure.ac:8:   'automake --add-missing' can install 'missing'
parallel-tests: error: required file './test-driver' not found
parallel-tests:   'automake --add-missing' can install 'test-driver'
src/Makefile.am: error: required file './depcomp' not found
src/Makefile.am:   'automake --add-missing' can install 'depcomp'
autoreconf: automake failed with exit status: 1
```

Executing `automake --add-missing` as suggested generated the remaining missing files, allowing `configure` to run to successful completion.

I don't think this is necessarily a problem with Austin. I think Manjaro is more user-focused than many other Linux distros (I switched to it from Ubuntu to try out a different - better? - UI) and doesn't always install everything a developer might expect to be present straight out of the box. I know I've installed a bunch of packages since spinning up Manjaro, much of which I don't recall needing to do on Ubuntu. I've never used Arch, upon which Manjaro is based, so can't comment on whether or not autoconf/automake packages would be installed by default. I do recall installing autoconf a while ago (no longer remember the context), but for whatever reason that was all I needed at that point.

Perhaps all that's needed is to amend the Build section of the docs to indicate that some systems might require installation of `autoconf` and/or `automake` packages along with execution of `automake --add-missing`. An alternative might be to include the necessary auxiliary files needed by `configure` so new users could just execute

```
git clone ...
configure && make
```

**Comment by P403n1x87** [comment]
Thanks for your report and for the detailed steps on how to build Austin from sources using autotools on Manjaro. I have created a VM with the latest version of the Arch Linux-based OS and experimented a bit. I have found that installing gcc and running

~~~ shell
gcc -O3 -Os -Wall -pthread src/*.c -o src/austin
~~~

does the trick. The reason why it's possible to build Austin with autotools is to _make it right_ so to say, but given the simplicity of the project, it's enough to just invoke gcc directly. Nonetheless, I'll enhance the README with a note for Manjaro based on your findings (otherwise feel free to open a PR yourself :smile:).

Thanks again for your contribution to Austin.
