### ISSUE TITLE
Windows install from chocolatey doesn't echo anything

### ISSUE THREAD

**Issue by tonybaloney** [P403n1x87/austin#86]
Installing austin from chocolatey on Windows installs a binary that doesn't echo or seem to do anything:

```console
> austin -V
> 
```

None of the example commands work, just doesn't give any output.

Version 3.0.0.

I'm on Windows 11 :-)

**Comment by tonybaloney** [comment]
Downloading and running the standalone .exe suggests `libwinpthread-1.dll` is missing. So its not statically linked in the compiler

**Comment by P403n1x87** [comment]
Thanks for reporting this! I never realised that MinGW pulled in that dependency even though `pthread` is not used on Windows. For now I'll make sure that that library is linked statically to the generated binaries in future releases.
