### ISSUE TITLE
Cannot launch the given command

### ISSUE THREAD

**Issue by justmytwospence** [P403n1x87/austin#90]
### Description

When I try to run the documented example: `austin -i 1ms ./test.py` on 

```
import psutil

for i in range(1000):
    list(psutil.process_iter())
```

I get the error

```
❌ Cannot launch the given command. Either it is not valid or the process
terminated too quickly.
```

### Steps to Reproduce

Given in description

**Expected behavior:** 
I expect the command to run.

**Actual behavior:** 
The above error message

**Reproduces how often:** 
100% of the time

### Versions

3.1.0 on Manjaro 21.1.5

**Comment by P403n1x87** [comment]
Thanks for confirming. Feel free to open another issue either here or on the [extension](https://github.com/p403n1x87/austin-vscode) repository if you still cannot get things to work as they should!
