### ISSUE TITLE
fail to infer tid offset

### ISSUE THREAD

**Issue by stphnlyd** [P403n1x87/austin#93]
### Description

I got this issue in one of my environment, which must be somewhat different from a normal one although I don't know what exactly could cause this. Under this envionment Austin gets no samples, and I debugged a little bit and see _pthread_tid_offset is 0 here https://github.com/P403n1x87/austin/blob/8dce4d29a3c293048ccc319eb48a20b153f638b4/src/py_thread.c#L453

I believe it won't reproduce on a normal Linux system. Here I only would like to see if you could have any ideas how I can further investigate it in my environment. 

### Versions

3.1.0

**Comment by P403n1x87** [comment]
This should have a fix for now, albeit not perfect. Please feel free to re-open if this is still an issue.
