### ISSUE TITLE
"Cannot determine the version of the Python interpreter" on Windows

### ISSUE THREAD

**Issue by basil96** [P403n1x87/austin#97]
### Description

I'm trying to use Austin on Windows.  I installed it, I have it on my PATH.  When trying to use it to profile a simple Python script, I get the error in the title.  I believe I'm pointing Austin to an actual Python executable, not to the `py` wrapper.

What am I doing wrong?

### Steps to Reproduce

1. Install latest Austin via MSI binary.
2. Create a `test.py` script with the following contents:
```python
total = 0
for i in range(1001):
    total += i
print(total)
```
3. Open commandline Terminal and run the following in the script's dir:
```batch
> austin --pipe "C:\Program Files\Python39\python.exe" test.py
```

**Expected behavior:** successful execution of script and some useful output from Austin for post-processing.

**Actual behavior:** Austin complains with the following:
```
🔢 Cannot determine the version of the Python interpreter. This could be due
to the binary not being an actual Python binary, like uWSGI. Please report an
issue at

    🌐 https://github.com/P403n1x87/austin/issues

together with details about the application that you were trying to profile,
like frameworks used, command line etc ....
```

**Reproduces how often:** 100%

### Versions

Python 3.9.6

austin 3.1.0

Windows 10:
Edition	Windows 10 Pro
Version	21H2
OS build	19044.1387

### Additional Information

Other command variations I've tried out of desperation:
```batch
> austin -C --pipe "C:\Program Files\Python39\python.exe" test.py
```
Response:
```
👽 Not a Python process.

🚼 It looks like you are trying to profile a process that is not a Python
process, and that has not spawned any child Python processes. Make sure that
you are targeting the right application.
```

And another:
```batch
> austin -C "C:\Program Files\Python39\python.exe" test.py
```
Response:
```
[1m              _   _      [0m
[1m __ _ _  _ __| |_(_)_ _  [0m
[1m/ _` | || (_-<  _| | ' \ [0m
[1m\__,_|\_,_/__/\__|_|_||_|[0m [36;1m3.1.0[0m

[1mParent process[0m
👽 Not a Python process.

🚼 It looks like you are trying to profile a process that is not a Python
process, and that has not spawned any child Python processes. Make sure that
you are targeting the right application.
```

**Comment by P403n1x87** [comment]
@basil96 thanks for reporting this. I suspect two things:

- the script runs for a short period and therefore finishes before Austin has a chance to profile it;
- Austin might have problems with white spaces in command lines on Windows. A fix has been merged into the [`devel`](https://github.com/P403n1x87/austin/commit/a11baa4006f19fdf7da9ffec495beea94a053207) branch and will be available with the next release (which should happen shortly :crossed_fingers:).

I'll try to confirm either of these once I get the chance to get on Windows.

**Comment by basil96** [comment]
Thank you for looking into this, @P403n1x87 

The first suspicion is probably not the case.  I had originally tried running Austin against a much longer-running script. The result brought me here. Austin was returning almost immediately.

Now I created a longer example `test.py`:

```python
import numpy as np

def process():
    a = np.random.random((5000, 10))
    b = np.random.random((10, 100))
    for row in a:
        x = a.dot(b)

process()
```

The results from Austin show the same issue.
For reference, I ran `cProfile` against it:

```batch
> python -m cProfile -s cumtime test.py > test.txt
```
Top results are:
```
         96014 function calls (93674 primitive calls) in 7.207 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    427/1    0.001    0.000    7.208    7.208 {built-in method builtins.exec}
        1    0.000    0.000    7.208    7.208 test.py:1(<module>)
        1    1.409    1.409    6.819    6.819 test.py:4(process)
     5001    5.410    0.001    5.410    0.001 {method 'dot' of 'numpy.ndarray' objects}
       13    0.001    0.000    0.796    0.061 __init__.py:1(<module>)
```

Looking forward to the next release.

**Comment by P403n1x87** [comment]
@basil96 I can confirm that the original script is too short-lived to be profiled on Windows. Changing it to
~~~ python
from time import sleep

total = 0
for i in range(1001):
    total += i
    sleep(0.0001)
print(total)
~~~
produces profiling data. So I believe this is due to the white space in the path. Are there any chances that you could try within a virtualenv in a path with no spaces? Otherwise, this will be fixed by the next release. Alternatively, you could checkout the `devel` branch and compile from sources for now.

**Comment by basil96** [comment]
Confirmed with a venv that has no spaces. Seems to be running as expected.
I appreciate your help!
